// supabase/functions/shared/agents/safety/copyright-review-agent.ts
// Copyright compliance agent — ensures no copyrighted exam materials are reproduced.

import type { AgentMetadata, AgentContext } from '../types.ts';
import { BaseLearningAgent } from '../base-agent.ts';
import { buildSystemPrompt } from '../prompt-loader.ts';

const metadata: AgentMetadata = {
  id: 'copyright-review',
  name: 'Copyright Compliance Reviewer',
  version: '1.0.0',
  description: 'Mandatory post-processor that ensures AI content never reproduces copyrighted exam materials.',
  category: 'safety',
  capabilities: ['copyright-review'],
  providers: ['gemini', 'openai'],
  costTier: 'low',
  maxTokens: 1024,
  temperature: 0.1,
  enabled: true,
};

export class CopyrightReviewAgent extends BaseLearningAgent {
  readonly metadata = metadata;

  buildPrompt(context: AgentContext): string {
    return buildSystemPrompt(context, `ROLE: Copyright compliance reviewer for educational content.
Your job is to ensure that AI-generated content NEVER reproduces copyrighted materials.

CHECK FOR:
1. Reproduction of actual exam questions from IELTS, PTE, TOEFL, Goethe, JLPT, TOPIK
2. Copying of published reading passages or listening scripts
3. Reproduction of textbook exercises or answer keys
4. Use of copyrighted scoring rubrics verbatim
5. Reproduction of trademarked exam format structures without transformation

RULES:
- All practice material MUST be original, generated by the AI
- Official exam names, band descriptors, and scoring criteria may be referenced
- Practice content should be INSPIRED BY official specs, not copied from them
- Reading passages and listening scripts must be entirely original
- If uncertain, err on the side of caution

WHAT IS ALLOWED:
- Referencing official exam names and structure
- Using CEFR level descriptors (which are public)
- Describing exam format in general terms
- Generating original practice material in exam style

OUTPUT FORMAT (respond ONLY with valid JSON):
{
  "compliant": boolean,
  "violations": ["list of copyright concerns found"],
  "original_content_verified": boolean,
  "flagged_segments": ["specific text segments that may be copyrighted"],
  "recommendations": ["suggested fixes to achieve compliance"]
}`);
  }
}

export function createCopyrightReviewAgent(): CopyrightReviewAgent {
  return new CopyrightReviewAgent();
}
