codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        flags:
          - flutter
    patch:
      default:
        target: 80%
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false

flags:
  flutter:
    paths:
      - frontend/lib/
    carryforward: true

ignore:
  - "frontend/**/*.freezed.dart"
  - "frontend/**/*.g.dart"
  - "frontend/test/**/*"
  - "frontend/integration_test/**/*"
  - "frontend/lib/main.dart"
  - "frontend/lib/app/bootstrap.dart"
